[package]
name = "chat-app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
actix-web-actors = "4"
actix = "0.13"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
tungstenite = "0.17"
url = "2.3"
reqwest = { version = "0.11", features = ["json"] }