[package]
name = "chat-app"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-tungstenite = "0.17"
futures-util = "0.3"
url = "2.2"
hex = "0.4"
sha2 = "0.10.5"
